#!/APSshare/anaconda3/x86_64/bin/python

import os
import subprocess as sp

def main(options):
  indent = '    '

  depth = options.depth
  args = options.args
  subs = options.submodules
  listRepos = options.listRepos
  
  validArgs = ['status', 'fetch', 'checkout', 'rebase', 'pull', 'remote', 'branch', 'stash', 'add', 'commit', 'mv', 'rm', 'reset', 'config']
  expertArgs = ['push', ]
  
  if len(args) > 0 and listRepos == True:
	  # Use an invalid git argument so only the project directories are printed
	  args[0] = 'check'
  
  # do something
  pwd = os.getcwd()
  
  print("{}".format(pwd))

  # find . -maxdepth 7 -type d -name ".git"

  # maxdepth:
  # 1 = pwd
  # 2 = projects are in pwd (normal for development)
  # 3 = projects are in subdirectory (normal for epics-motor and github forks)

  findArgs = ['find', pwd, '-maxdepth', depth, '-name', '.git']
  
  if subs == False:
	  # submodules have .git files; modules have .git directories
	  findArgs += ['-type', 'd']

  completed = sp.run(findArgs, stdout=sp.PIPE)
  print("returncode: {}".format(completed.returncode))
  #!print('Have {} bytes in stdout:\n{}'.format(
  #!  len(completed.stdout),
  #!  completed.stdout.decode('utf-8'))
  #!)
  
  # output is a new-line delimited string
  output = completed.stdout.decode('utf-8')

  lineList = output.split("\n")
  sortedList = sorted(lineList)

  for line in sortedList:
    if line != '':
      # print the path without the .git dir
      project = os.path.dirname(line)
      print("{} - {}".format(os.path.basename(project), project))

      if len(args) > 0 and args[0] in validArgs:
        os.chdir(project)

        cmd = ['git',] + args
        #!print(cmd)
        g_comp = sp.run(cmd, stdout=sp.PIPE)
        g_output = g_comp.stdout.decode('utf-8')
        # Indent the git output
        outLines = g_output.split('\n')
        for outLine in outLines:
          if '#   (' in outLine:
            continue
          else:
            print(indent+outLine)
        #!print()

        os.chdir(pwd)

  # git status | grep -v '(use'


if __name__ == '__main__':
    import sys
    import argparse
    parser = argparse.ArgumentParser("git-all")
      
    parser.add_argument("-d", action="store", default="6", required=False, dest='depth',  help='max search depth (used by the find command)')
    parser.add_argument("-s", action="store_true", required=False, dest='submodules',     help='include submodules')
    parser.add_argument("-l", action="store_true",  required=False, dest='listRepos',     help='list repos')
    parser.add_argument("args", action="store", default=None, nargs=argparse.REMAINDER,  help='git command to execute in each repo')

    options = parser.parse_args(sys.argv[1:])
    print(options)
    
    main(options)
